---
- name: start pretend redis server from scratch
  hosts: db_servers
  remote_user: ec2-user
  tasks:
    - name: update
      yum:
        name: '*'
        state: latest
      become: yes
    - name: install db
      yum: 
        name: redis
        state: latest
      become: yes
