---
- name: update all servers
  hosts: all_servers
  remote_user: ec2-user
  tasks:
    - name: update all packages to latest version
      yum:
        name: '*'
        state: latest
      become: yes
