---
- name: Install web service and start website
  hosts: web_servers
  remote_user: ec2-user
  tasks:
    - name: install apache 
      yum:
        name: httpd
        state: latest
      become: yes
    - name: create index file 
      shell: echo "<html>Website coming soon!</html>" > /var/www/html/index.html
      become: yes
    - name: ensure apache is running
      service:
        name:  httpd
        state: started
      become: yes
