---
- name: start web server from scratch
  hosts: web_servers
  remote_user: ec2-user
  tasks:
    - name: update
      yum:
        name: '*'
        state: latest
      become: yes
    - name: install apache 
      yum:
        name: httpd
        state: latest
      become: yes
    - name: ensure apache is running
      service:
        name:  httpd
        state: started
      become: yes
    - name: create index
      shell: echo "<html>Website coming soon!</html>" > /var/www/html/index.html
      become: yes
#     handlers: 
#     - name: restart apache
#        service:
#          name: httpd
#          state: restarted
